# Each new term in the Fibonacci sequence is
# generated by adding the previous two terms.
# By starting
# with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci
# sequence whose values do not exceed four million
# , find the sum of the even-valued terms.



class Practicing:

    def fib(self):
        first = 1
        second = 2
        temp = 0
        count=0
        while(count < 20):
            print(first)
            temp = first + second
            first = second
            second = temp
            count+=1







def main():
    jadi = Practicing()
    jadi.fib()




if __name__ == '__main__':main()
